package scan

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// GenerateYAML builds a policy scaffold YAML from a list of MCP tools.
// The output includes per-tool comments with descriptions and parameter
// summaries, and a commented-out global rate limit wildcard example.
func GenerateYAML(tools []MCPTool, serverName string) ([]byte, error) {
	sort.Slice(tools, func(i, j int) bool {
		return tools[i].Name < tools[j].Name
	})

	doc := &yaml.Node{Kind: yaml.DocumentNode}
	root := &yaml.Node{Kind: yaml.MappingNode}
	doc.Content = append(doc.Content, root)

	// Header comment.
	toolCount := len(tools)
	now := time.Now().UTC().Format(time.RFC3339)
	header := fmt.Sprintf(
		" Generated by: intercept scan -- %s\n Tools discovered: %d\n Date: %s\n\n Each tool is listed with its description and parameters.\n Add rules to enforce policy. See: https://github.com/policylayer/intercept",
		serverName, toolCount, now,
	)
	root.HeadComment = header

	// version: "1"
	root.Content = append(root.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: "version"},
		&yaml.Node{Kind: yaml.ScalarNode, Value: "1", Style: yaml.DoubleQuotedStyle},
	)

	// description
	desc := fmt.Sprintf("Policy for %s", serverName)
	root.Content = append(root.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: "description"},
		&yaml.Node{Kind: yaml.ScalarNode, Value: desc, Style: yaml.DoubleQuotedStyle},
	)

	// default: "allow" with a hint about deny mode
	defaultKey := &yaml.Node{Kind: yaml.ScalarNode, Value: "default"}
	defaultKey.HeadComment = " Set to \"deny\" to reject tool calls not listed below"
	defaultVal := &yaml.Node{Kind: yaml.ScalarNode, Value: "allow", Style: yaml.DoubleQuotedStyle}
	root.Content = append(root.Content, defaultKey, defaultVal)

	// tools map
	toolsKey := &yaml.Node{Kind: yaml.ScalarNode, Value: "tools"}
	toolsMap := &yaml.Node{Kind: yaml.MappingNode}

	for _, tool := range tools {
		comment := buildToolComment(tool)

		nameNode := &yaml.Node{Kind: yaml.ScalarNode, Value: tool.Name}
		nameNode.HeadComment = comment

		valueNode := &yaml.Node{Kind: yaml.MappingNode}
		valueNode.Content = append(valueNode.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: "rules"},
			&yaml.Node{Kind: yaml.SequenceNode, Style: yaml.FlowStyle},
		)

		toolsMap.Content = append(toolsMap.Content, nameNode, valueNode)
	}

	root.Content = append(root.Content, toolsKey, toolsMap)

	out, err := yaml.Marshal(doc)
	if err != nil {
		return nil, fmt.Errorf("marshalling YAML: %w", err)
	}

	// Append the wildcard rate limit example as a comment block so it
	// doesn't silently apply to every call. Users uncomment it to opt in.
	out = append(out, wildcardComment...)

	return out, nil
}

// buildToolComment produces a YAML comment block for a tool, including its
// description and a summary of its parameters.
func buildToolComment(tool MCPTool) string {
	var parts []string
	desc := tool.Name
	if tool.Description != "" {
		desc += ": " + tool.Description
	}
	parts = append(parts, " "+desc)

	paramSummary := extractParamSummary(tool.InputSchema)
	if paramSummary != "" {
		for _, line := range wrapLine(paramSummary, 70) {
			parts = append(parts, "   "+line)
		}
	}

	return strings.Join(parts, "\n")
}

// extractParamSummary reads a JSON Schema object and returns a human-readable
// parameter summary like "owner (string, required), repo (string)".
func extractParamSummary(schema map[string]any) string {
	if schema == nil {
		return ""
	}

	propsRaw, ok := schema["properties"]
	if !ok {
		return ""
	}
	props, ok := propsRaw.(map[string]any)
	if !ok {
		return ""
	}

	var required map[string]bool
	if reqRaw, ok := schema["required"]; ok {
		if reqList, ok := reqRaw.([]any); ok {
			required = make(map[string]bool, len(reqList))
			for _, r := range reqList {
				if s, ok := r.(string); ok {
					required[s] = true
				}
			}
		}
	}

	type param struct {
		name     string
		typ      string
		required bool
	}

	var params []param
	for name, propRaw := range props {
		typ := "any"
		if propMap, ok := propRaw.(map[string]any); ok {
			if t, ok := propMap["type"].(string); ok {
				typ = t
			}
		}
		params = append(params, param{
			name:     name,
			typ:      typ,
			required: required[name],
		})
	}

	// Sort: required first (alphabetically), then optional (alphabetically).
	sort.Slice(params, func(i, j int) bool {
		if params[i].required != params[j].required {
			return params[i].required
		}
		return params[i].name < params[j].name
	})

	var parts []string
	for _, p := range params {
		s := p.name + " (" + p.typ
		if p.required {
			s += ", required"
		}
		s += ")"
		parts = append(parts, s)
	}

	return strings.Join(parts, ", ")
}

// wrapLine splits a string into lines of at most maxLen characters,
// breaking at comma boundaries where possible.
func wrapLine(s string, maxLen int) []string {
	if len(s) <= maxLen {
		return []string{s}
	}

	var lines []string
	for len(s) > maxLen {
		// Find the last comma+space within maxLen.
		cut := -1
		for i := maxLen - 1; i >= 0; i-- {
			if i+1 < len(s) && s[i] == ',' && s[i+1] == ' ' {
				cut = i + 2 // include the comma and space
				break
			}
		}
		if cut <= 0 {
			cut = maxLen
		}
		lines = append(lines, s[:cut])
		s = s[cut:]
	}
	if len(s) > 0 {
		lines = append(lines, s)
	}
	return lines
}

var wildcardComment = []byte(`
  # Uncomment to apply a global rate limit across all tools:
  # "*":
  #   rules:
  #     - name: "global rate limit"
  #       rate_limit: 60/minute
`)
