package scan

import (
	"os"
	"strings"
	"testing"

	"github.com/policylayer/intercept/internal/config"
)

func TestGenerateYAML(t *testing.T) {
	tools := []MCPTool{
		{
			Name:        "delete_repository",
			Description: "Permanently delete a repository",
			InputSchema: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"owner": map[string]any{"type": "string"},
					"repo":  map[string]any{"type": "string"},
				},
				"required": []any{"owner", "repo"},
			},
		},
		{
			Name:        "create_issue",
			Description: "Create a new issue in a GitHub repository",
			InputSchema: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"owner":  map[string]any{"type": "string"},
					"repo":   map[string]any{"type": "string"},
					"title":  map[string]any{"type": "string"},
					"body":   map[string]any{"type": "string"},
					"labels": map[string]any{"type": "array"},
				},
				"required": []any{"owner", "repo", "title"},
			},
		},
		{
			Name:        "get_issue",
			Description: "Get details of a specific issue",
			InputSchema: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"owner":        map[string]any{"type": "string"},
					"repo":         map[string]any{"type": "string"},
					"issue_number": map[string]any{"type": "number"},
				},
				"required": []any{"owner", "repo", "issue_number"},
			},
		},
	}

	out, err := GenerateYAML(tools, "npx @modelcontextprotocol/server-github")
	if err != nil {
		t.Fatalf("GenerateYAML() error: %v", err)
	}

	s := string(out)

	// Tools should be sorted alphabetically.
	createIdx := strings.Index(s, "create_issue:")
	deleteIdx := strings.Index(s, "delete_repository:")
	getIdx := strings.Index(s, "get_issue:")
	if createIdx < 0 || deleteIdx < 0 || getIdx < 0 {
		t.Fatalf("missing tool entries in output:\n%s", s)
	}
	if createIdx > deleteIdx || deleteIdx > getIdx {
		t.Error("tools are not sorted alphabetically")
	}

	// Check header comment.
	if !strings.Contains(s, "Generated by: intercept scan") {
		t.Error("missing header comment")
	}
	if !strings.Contains(s, "Tools discovered: 3") {
		t.Error("missing tool count in header")
	}

	// Check tool descriptions appear as comments.
	if !strings.Contains(s, "Create a new issue") {
		t.Error("missing create_issue description")
	}
	if !strings.Contains(s, "Permanently delete") {
		t.Error("missing delete_repository description")
	}

	// Check parameter summaries.
	if !strings.Contains(s, "owner (string, required)") {
		t.Error("missing parameter summary with required marker")
	}
	if !strings.Contains(s, "body (string)") {
		t.Error("missing optional parameter in summary")
	}

	// Check default field hint.
	if !strings.Contains(s, `Set to "deny"`) {
		t.Error("missing default: deny hint comment")
	}
	if !strings.Contains(s, `default: "allow"`) {
		t.Error("missing default: allow field")
	}

	// Check commented-out wildcard example.
	if !strings.Contains(s, `# "*":`) {
		t.Error("missing commented-out wildcard entry")
	}
	if !strings.Contains(s, "# Uncomment to apply a global rate limit") {
		t.Error("missing wildcard instruction comment")
	}
	if !strings.Contains(s, "global rate limit") {
		t.Error("missing global rate limit rule in comment")
	}
	if !strings.Contains(s, "rate_limit: 60/minute") {
		t.Error("missing rate_limit shorthand in comment")
	}

	// Check version.
	if !strings.Contains(s, `version: "1"`) {
		t.Error("missing version field")
	}
}

func TestGenerateYAMLEmptyTools(t *testing.T) {
	out, err := GenerateYAML(nil, "empty-server")
	if err != nil {
		t.Fatalf("GenerateYAML() error: %v", err)
	}

	s := string(out)

	if !strings.Contains(s, "Tools discovered: 0") {
		t.Error("expected 0 tools in header")
	}
	if !strings.Contains(s, `# "*":`) {
		t.Error("commented-out wildcard should still be present")
	}
	if !strings.Contains(s, `version: "1"`) {
		t.Error("version should be present")
	}
}

func TestParameterSummary(t *testing.T) {
	tests := []struct {
		name   string
		schema map[string]any
		want   string
	}{
		{
			name:   "nil schema",
			schema: nil,
			want:   "",
		},
		{
			name:   "no properties",
			schema: map[string]any{"type": "object"},
			want:   "",
		},
		{
			name: "mixed required and optional",
			schema: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"name":  map[string]any{"type": "string"},
					"id":    map[string]any{"type": "number"},
					"debug": map[string]any{"type": "boolean"},
				},
				"required": []any{"id"},
			},
			want: "id (number, required), debug (boolean), name (string)",
		},
		{
			name: "all required",
			schema: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"b": map[string]any{"type": "string"},
					"a": map[string]any{"type": "string"},
				},
				"required": []any{"a", "b"},
			},
			want: "a (string, required), b (string, required)",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := extractParamSummary(tt.schema)
			if got != tt.want {
				t.Errorf("extractParamSummary() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestGenerateYAMLValidPolicy(t *testing.T) {
	tools := []MCPTool{
		{
			Name:        "test_tool",
			Description: "A test tool",
			InputSchema: map[string]any{
				"type":       "object",
				"properties": map[string]any{"arg1": map[string]any{"type": "string"}},
			},
		},
	}

	out, err := GenerateYAML(tools, "test-server")
	if err != nil {
		t.Fatalf("GenerateYAML() error: %v", err)
	}

	// Write to temp file and load through config.Load (which applies defaults).
	tmpFile := t.TempDir() + "/policy.yaml"
	if err := os.WriteFile(tmpFile, out, 0o644); err != nil {
		t.Fatalf("writing temp file: %v", err)
	}

	cfg, err := config.Load(tmpFile)
	if err != nil {
		t.Fatalf("generated YAML is not loadable: %v\n\nOutput:\n%s", err, string(out))
	}

	// Validate the config.
	errs := config.Validate(cfg)
	if len(errs) > 0 {
		t.Errorf("generated policy has validation errors:")
		for _, e := range errs {
			t.Errorf("  %v", e)
		}
		t.Logf("Output:\n%s", string(out))
	}

	// Verify structure.
	if cfg.Version != "1" {
		t.Errorf("version = %q, want %q", cfg.Version, "1")
	}
	if _, ok := cfg.Tools["test_tool"]; !ok {
		t.Error("missing test_tool in parsed config")
	}
	// Wildcard is commented out, so it should NOT appear in the parsed config.
	if _, ok := cfg.Tools["*"]; ok {
		t.Error("wildcard should be commented out, not active")
	}
}

func TestWrapLine(t *testing.T) {
	tests := []struct {
		input  string
		maxLen int
		want   int // expected number of lines
	}{
		{"short", 70, 1},
		{"a (string, required), b (string, required), c (string), d (string), e (string), f (string)", 70, 2},
	}

	for _, tt := range tests {
		lines := wrapLine(tt.input, tt.maxLen)
		if len(lines) != tt.want {
			t.Errorf("wrapLine(%q, %d) = %d lines, want %d: %v", tt.input, tt.maxLen, len(lines), tt.want, lines)
		}
		for i, line := range lines {
			if i < len(lines)-1 && len(line) > tt.maxLen {
				t.Errorf("line %d exceeds maxLen %d: %q (%d chars)", i, tt.maxLen, line, len(line))
			}
		}
	}
}
